import Head from "next/head";


import styled from "styled-components";
import Login from "@/components/login/login";
import Heading from "@/components/heading/heading";
import CreateBurger from "@/components/create/create";
import SmallMenu from "@/components/menu_small/menu";

const Grid = styled.div`
  outline: 1px solid dodgerblue;
  display: grid;
  grid-template-columns: 1fr 1fr;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Burger Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
      <Heading />
      <Grid>
        <CreateBurger />

        <SmallMenu/>
      </Grid>
    </>
  );
}
