import Head from 'next/head'

import { Inter } from 'next/font/google'
import styled from 'styled-components'
import Login from '@/components/login/login'
import Heading from '@/components/heading/heading'


const Grid = styled.div`
outline: 1px solid dodgerblue;
display:grid;
grid-template-columns: 1fr repeat(2);


`






export default function Home() {


  return (
    <>
      <Head>
        <title>Burger Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
         <Login/>
      <Heading/>
   <Grid/>
          
    </>
  )
}
